# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml 
steps:

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'storage', 'cp', '-r','${_BUCKET}', '.']

- name: 'gcr.io/${PROJECT_ID}/gcluster'
  args: [
    'destroy',
    'tf', 
    '--auto-approve'
    ]    
substitutions:
    _BUCKET:  # Provide your own bucket URL gs://      
tags: ['cloud-builders-community']
